version: "3.9"

# to run this (from this directory):

# docker compose v1:
# docker-compose up --build

#docker compose v2:
# docker compose up --build

# to run the keeper install fluxvault and then from the top directory of this repo run:

# fluxvault keeper --agent-ips 127.0.0.1 --managed-files quotes.txt --vault-dir examples/files --sign-connections --zelid 1GKugrE8cmw9NysWFJPwszBbETRLwLaLmM --polling-interval 20

# you should then get prompted for the private key.. use the following:

# Kwd2NvAavdEjYFWj299R6csDyoFeQsLvH5ZkN1Bb8jQcf1e8Qre7

services:
  fluxagent:
    container_name: fluxfluxagent_apptime
    build: .
    ports:
      - "8888:8888"
    command: fluxvault agent --signed-vault-connections --zelid 1GKugrE8cmw9NysWFJPwszBbETRLwLaLmM --registrar
    networks:
      agent:
      internet:
        ipv4_address: 192.168.74.44
  cool_container_1:
    container_name: fluxcontainer1_apptime
    build: .
    depends_on:
      - fluxagent
    command: fluxvault agent --signed-vault-connections --zelid 1GKugrE8cmw9NysWFJPwszBbETRLwLaLmM --subordinate
    networks:
      - agent
  cool_container_2:
    container_name: fluxcontainer2_apptime
    build: .
    depends_on:
      - fluxagent
    command: fluxvault agent --signed-vault-connections --zelid 1GKugrE8cmw9NysWFJPwszBbETRLwLaLmM --subordinate
    networks:
      - agent
networks:
  internet:
    ipam:
      driver: default
      config:
        - subnet: "192.168.74.0/24"
  agent:
